(define defs '(
SDL_INIT_AUDIO
SDL_INIT_VIDEO
SDL_INIT_TIMER
SDL_INIT_JOYSTICK
SDL_INIT_HAPTIC
SDL_INIT_GAMECONTROLLER
SDL_INIT_EVENTS
SDL_INIT_EVERYTHING
SDL_INIT_NOPARACHUTE

SDL_HINT_DEFAULT
SDL_HINT_NORMAL
SDL_HINT_OVERRIDE
SDL_HINT_FRAMEBUFFER_ACCELERATION
SDL_HINT_IDLE_TIMER_DISABLED
SDL_HINT_ORIENTATIONS
SDL_HINT_RENDER_DRIVER
SDL_HINT_RENDER_OPENGL_SHADERS
SDL_HINT_RENDER_SCALE_QUALITY
SDL_HINT_RENDER_VSYNC

SDL_LOG_CATEGORY_APPLICATION
SDL_LOG_CATEGORY_ERROR
SDL_LOG_CATEGORY_SYSTEM
SDL_LOG_CATEGORY_AUDIO
SDL_LOG_CATEGORY_VIDEO
SDL_LOG_CATEGORY_RENDER
SDL_LOG_CATEGORY_INPUT
SDL_LOG_CATEGORY_CUSTOM

SDL_LOG_PRIORITY_VERBOSE
SDL_LOG_PRIORITY_DEBUG
SDL_LOG_PRIORITY_INFO
SDL_LOG_PRIORITY_WARN
SDL_LOG_PRIORITY_ERROR
SDL_LOG_PRIORITY_CRITICAL

SDL_WINDOWPOS_CENTERED
SDL_WINDOWPOS_UNDEFINED

SDL_WINDOW_FULLSCREEN
SDL_WINDOW_FULLSCREEN_DESKTOP
SDL_WINDOW_OPENGL
SDL_WINDOW_SHOWN
SDL_WINDOW_HIDDEN
SDL_WINDOW_BORDERLESS
SDL_WINDOW_RESIZABLE
SDL_WINDOW_MINIMIZED
SDL_WINDOW_MAXIMIZED
SDL_WINDOW_INPUT_GRABBED
SDL_WINDOW_INPUT_FOCUS
SDL_WINDOW_MOUSE_FOCUS
SDL_WINDOW_FOREIGN

;SDL_WINDOW_ALLOW_HIGHDPI

SDL_GL_RED_SIZE
SDL_GL_GREEN_SIZE
SDL_GL_BLUE_SIZE
SDL_GL_ALPHA_SIZE
SDL_GL_BUFFER_SIZE
SDL_GL_DOUBLEBUFFER
SDL_GL_DEPTH_SIZE
SDL_GL_STENCIL_SIZE
SDL_GL_ACCUM_RED_SIZE
SDL_GL_ACCUM_GREEN_SIZE
SDL_GL_ACCUM_BLUE_SIZE
SDL_GL_ACCUM_ALPHA_SIZE
SDL_GL_STEREO
SDL_GL_MULTISAMPLEBUFFERS
SDL_GL_MULTISAMPLESAMPLES
SDL_GL_ACCELERATED_VISUAL
SDL_GL_RETAINED_BACKING
SDL_GL_CONTEXT_MAJOR_VERSION
SDL_GL_CONTEXT_MINOR_VERSION
SDL_GL_CONTEXT_EGL
SDL_GL_CONTEXT_FLAGS
SDL_GL_CONTEXT_PROFILE_MASK
SDL_GL_SHARE_WITH_CURRENT_CONTEXT

SDL_WINDOW_FULLSCREEN
SDL_WINDOW_FULLSCREEN_DESKTOP

SDL_QUIT
SDL_APP_TERMINATING
SDL_APP_LOWMEMORY
SDL_APP_WILLENTERBACKGROUND
SDL_APP_DIDENTERBACKGROUND
SDL_APP_WILLENTERFOREGROUND
SDL_APP_DIDENTERFOREGROUND
SDL_WINDOWEVENT
SDL_SYSWMEVENT
SDL_KEYDOWN
SDL_KEYUP
SDL_TEXTEDITING
SDL_TEXTINPUT
SDL_MOUSEMOTION
SDL_MOUSEBUTTONDOWN
SDL_MOUSEBUTTONUP
SDL_MOUSEWHEEL
SDL_JOYAXISMOTION
SDL_JOYBALLMOTION
SDL_JOYHATMOTION
SDL_JOYBUTTONDOWN
SDL_JOYBUTTONUP
SDL_JOYDEVICEADDED
SDL_JOYDEVICEREMOVED
SDL_CONTROLLERAXISMOTION
SDL_CONTROLLERBUTTONDOWN
SDL_CONTROLLERBUTTONUP
SDL_CONTROLLERDEVICEADDED
SDL_CONTROLLERDEVICEREMOVED
SDL_CONTROLLERDEVICEREMAPPED
SDL_FINGERDOWN
SDL_FINGERUP
SDL_FINGERMOTION
SDL_DOLLARGESTURE
SDL_DOLLARRECORD
SDL_MULTIGESTURE
SDL_CLIPBOARDUPDATE
SDL_DROPFILE
SDL_USEREVENT

SDL_PIXELFORMAT_UNKNOWN
SDL_PIXELFORMAT_INDEX1LSB
SDL_PIXELFORMAT_INDEX1MSB
SDL_PIXELFORMAT_INDEX4LSB
SDL_PIXELFORMAT_INDEX4MSB
SDL_PIXELFORMAT_INDEX8
SDL_PIXELFORMAT_RGB332
SDL_PIXELFORMAT_RGB444
SDL_PIXELFORMAT_RGB555
SDL_PIXELFORMAT_BGR555
SDL_PIXELFORMAT_ARGB4444
SDL_PIXELFORMAT_RGBA4444
SDL_PIXELFORMAT_ABGR4444
SDL_PIXELFORMAT_BGRA4444
SDL_PIXELFORMAT_ARGB1555
SDL_PIXELFORMAT_RGBA5551
SDL_PIXELFORMAT_ABGR1555
SDL_PIXELFORMAT_BGRA5551
SDL_PIXELFORMAT_RGB565
SDL_PIXELFORMAT_BGR565
SDL_PIXELFORMAT_RGB24
SDL_PIXELFORMAT_BGR24
SDL_PIXELFORMAT_RGB888
SDL_PIXELFORMAT_RGBX8888
SDL_PIXELFORMAT_BGR888
SDL_PIXELFORMAT_BGRX8888
SDL_PIXELFORMAT_ARGB8888
SDL_PIXELFORMAT_RGBA8888
SDL_PIXELFORMAT_ABGR8888
SDL_PIXELFORMAT_BGRA8888
SDL_PIXELFORMAT_ARGB2101010
SDL_PIXELFORMAT_YV12
SDL_PIXELFORMAT_IYUV
SDL_PIXELFORMAT_YUY2
SDL_PIXELFORMAT_UYVY
SDL_PIXELFORMAT_YVYU

SDL_TEXTUREACCESS_STATIC
SDL_TEXTUREACCESS_STREAMING
))

(use irregex)

(print "(module sdl2-defs")
(print "(")
(for-each
 (lambda (s)
   (let ((name (symbol->string s)))
     (print (irregex-replace/all "[_]" name "-"))))
 defs)
(print ")")
(print "(import scheme chicken foreign)")

(print "#>")
(print "#include <SDL2/SDL.h>")
(print "#include <SDL2/SDL_video.h>")
(print "#include <SDL2/SDL_render.h>")
(print "#include <SDL2/SDL_hints.h>")
(print "#include <SDL2/SDL_error.h>")
(print "#include <SDL2/SDL_log.h>")
(print "#include <SDL2/SDL_version.h>")
(print "<#")

(for-each
 (lambda (s)
  (let ((name (symbol->string s)))
    (print (sprintf "(define ~A (foreign-value \"~A\" int))"
                    (irregex-replace/all "[_]" name "-") name))))
 defs)


(print ")")
