(module sdl2-defs
(
SDL-INIT-AUDIO
SDL-INIT-VIDEO
SDL-INIT-TIMER
SDL-INIT-JOYSTICK
SDL-INIT-HAPTIC
SDL-INIT-GAMECONTROLLER
SDL-INIT-EVENTS
SDL-INIT-EVERYTHING
SDL-INIT-NOPARACHUTE
SDL-HINT-DEFAULT
SDL-HINT-NORMAL
SDL-HINT-OVERRIDE
SDL-HINT-FRAMEBUFFER-ACCELERATION
SDL-HINT-IDLE-TIMER-DISABLED
SDL-HINT-ORIENTATIONS
SDL-HINT-RENDER-DRIVER
SDL-HINT-RENDER-OPENGL-SHADERS
SDL-HINT-RENDER-SCALE-QUALITY
SDL-HINT-RENDER-VSYNC
SDL-LOG-CATEGORY-APPLICATION
SDL-LOG-CATEGORY-ERROR
SDL-LOG-CATEGORY-SYSTEM
SDL-LOG-CATEGORY-AUDIO
SDL-LOG-CATEGORY-VIDEO
SDL-LOG-CATEGORY-RENDER
SDL-LOG-CATEGORY-INPUT
SDL-LOG-CATEGORY-CUSTOM
SDL-LOG-PRIORITY-VERBOSE
SDL-LOG-PRIORITY-DEBUG
SDL-LOG-PRIORITY-INFO
SDL-LOG-PRIORITY-WARN
SDL-LOG-PRIORITY-ERROR
SDL-LOG-PRIORITY-CRITICAL
SDL-WINDOWPOS-CENTERED
SDL-WINDOWPOS-UNDEFINED
SDL-WINDOW-FULLSCREEN
SDL-WINDOW-FULLSCREEN-DESKTOP
SDL-WINDOW-OPENGL
SDL-WINDOW-SHOWN
SDL-WINDOW-HIDDEN
SDL-WINDOW-BORDERLESS
SDL-WINDOW-RESIZABLE
SDL-WINDOW-MINIMIZED
SDL-WINDOW-MAXIMIZED
SDL-WINDOW-INPUT-GRABBED
SDL-WINDOW-INPUT-FOCUS
SDL-WINDOW-MOUSE-FOCUS
SDL-WINDOW-FOREIGN
SDL-GL-RED-SIZE
SDL-GL-GREEN-SIZE
SDL-GL-BLUE-SIZE
SDL-GL-ALPHA-SIZE
SDL-GL-BUFFER-SIZE
SDL-GL-DOUBLEBUFFER
SDL-GL-DEPTH-SIZE
SDL-GL-STENCIL-SIZE
SDL-GL-ACCUM-RED-SIZE
SDL-GL-ACCUM-GREEN-SIZE
SDL-GL-ACCUM-BLUE-SIZE
SDL-GL-ACCUM-ALPHA-SIZE
SDL-GL-STEREO
SDL-GL-MULTISAMPLEBUFFERS
SDL-GL-MULTISAMPLESAMPLES
SDL-GL-ACCELERATED-VISUAL
SDL-GL-RETAINED-BACKING
SDL-GL-CONTEXT-MAJOR-VERSION
SDL-GL-CONTEXT-MINOR-VERSION
SDL-GL-CONTEXT-EGL
SDL-GL-CONTEXT-FLAGS
SDL-GL-CONTEXT-PROFILE-MASK
SDL-GL-SHARE-WITH-CURRENT-CONTEXT
SDL-WINDOW-FULLSCREEN
SDL-WINDOW-FULLSCREEN-DESKTOP
SDL-QUIT
SDL-APP-TERMINATING
SDL-APP-LOWMEMORY
SDL-APP-WILLENTERBACKGROUND
SDL-APP-DIDENTERBACKGROUND
SDL-APP-WILLENTERFOREGROUND
SDL-APP-DIDENTERFOREGROUND
SDL-WINDOWEVENT
SDL-SYSWMEVENT
SDL-KEYDOWN
SDL-KEYUP
SDL-TEXTEDITING
SDL-TEXTINPUT
SDL-MOUSEMOTION
SDL-MOUSEBUTTONDOWN
SDL-MOUSEBUTTONUP
SDL-MOUSEWHEEL
SDL-JOYAXISMOTION
SDL-JOYBALLMOTION
SDL-JOYHATMOTION
SDL-JOYBUTTONDOWN
SDL-JOYBUTTONUP
SDL-JOYDEVICEADDED
SDL-JOYDEVICEREMOVED
SDL-CONTROLLERAXISMOTION
SDL-CONTROLLERBUTTONDOWN
SDL-CONTROLLERBUTTONUP
SDL-CONTROLLERDEVICEADDED
SDL-CONTROLLERDEVICEREMOVED
SDL-CONTROLLERDEVICEREMAPPED
SDL-FINGERDOWN
SDL-FINGERUP
SDL-FINGERMOTION
SDL-DOLLARGESTURE
SDL-DOLLARRECORD
SDL-MULTIGESTURE
SDL-CLIPBOARDUPDATE
SDL-DROPFILE
SDL-USEREVENT
SDL-PIXELFORMAT-UNKNOWN
SDL-PIXELFORMAT-INDEX1LSB
SDL-PIXELFORMAT-INDEX1MSB
SDL-PIXELFORMAT-INDEX4LSB
SDL-PIXELFORMAT-INDEX4MSB
SDL-PIXELFORMAT-INDEX8
SDL-PIXELFORMAT-RGB332
SDL-PIXELFORMAT-RGB444
SDL-PIXELFORMAT-RGB555
SDL-PIXELFORMAT-BGR555
SDL-PIXELFORMAT-ARGB4444
SDL-PIXELFORMAT-RGBA4444
SDL-PIXELFORMAT-ABGR4444
SDL-PIXELFORMAT-BGRA4444
SDL-PIXELFORMAT-ARGB1555
SDL-PIXELFORMAT-RGBA5551
SDL-PIXELFORMAT-ABGR1555
SDL-PIXELFORMAT-BGRA5551
SDL-PIXELFORMAT-RGB565
SDL-PIXELFORMAT-BGR565
SDL-PIXELFORMAT-RGB24
SDL-PIXELFORMAT-BGR24
SDL-PIXELFORMAT-RGB888
SDL-PIXELFORMAT-RGBX8888
SDL-PIXELFORMAT-BGR888
SDL-PIXELFORMAT-BGRX8888
SDL-PIXELFORMAT-ARGB8888
SDL-PIXELFORMAT-RGBA8888
SDL-PIXELFORMAT-ABGR8888
SDL-PIXELFORMAT-BGRA8888
SDL-PIXELFORMAT-ARGB2101010
SDL-PIXELFORMAT-YV12
SDL-PIXELFORMAT-IYUV
SDL-PIXELFORMAT-YUY2
SDL-PIXELFORMAT-UYVY
SDL-PIXELFORMAT-YVYU
SDL-TEXTUREACCESS-STATIC
SDL-TEXTUREACCESS-STREAMING
)
(import scheme chicken foreign)
#>
#include <SDL2/SDL.h>
#include <SDL2/SDL_video.h>
#include <SDL2/SDL_render.h>
#include <SDL2/SDL_hints.h>
#include <SDL2/SDL_error.h>
#include <SDL2/SDL_log.h>
#include <SDL2/SDL_version.h>
<#
(define SDL-INIT-AUDIO (foreign-value "SDL_INIT_AUDIO" int))
(define SDL-INIT-VIDEO (foreign-value "SDL_INIT_VIDEO" int))
(define SDL-INIT-TIMER (foreign-value "SDL_INIT_TIMER" int))
(define SDL-INIT-JOYSTICK (foreign-value "SDL_INIT_JOYSTICK" int))
(define SDL-INIT-HAPTIC (foreign-value "SDL_INIT_HAPTIC" int))
(define SDL-INIT-GAMECONTROLLER (foreign-value "SDL_INIT_GAMECONTROLLER" int))
(define SDL-INIT-EVENTS (foreign-value "SDL_INIT_EVENTS" int))
(define SDL-INIT-EVERYTHING (foreign-value "SDL_INIT_EVERYTHING" int))
(define SDL-INIT-NOPARACHUTE (foreign-value "SDL_INIT_NOPARACHUTE" int))
(define SDL-HINT-DEFAULT (foreign-value "SDL_HINT_DEFAULT" int))
(define SDL-HINT-NORMAL (foreign-value "SDL_HINT_NORMAL" int))
(define SDL-HINT-OVERRIDE (foreign-value "SDL_HINT_OVERRIDE" int))
(define SDL-HINT-FRAMEBUFFER-ACCELERATION (foreign-value "SDL_HINT_FRAMEBUFFER_ACCELERATION" int))
(define SDL-HINT-IDLE-TIMER-DISABLED (foreign-value "SDL_HINT_IDLE_TIMER_DISABLED" int))
(define SDL-HINT-ORIENTATIONS (foreign-value "SDL_HINT_ORIENTATIONS" int))
(define SDL-HINT-RENDER-DRIVER (foreign-value "SDL_HINT_RENDER_DRIVER" int))
(define SDL-HINT-RENDER-OPENGL-SHADERS (foreign-value "SDL_HINT_RENDER_OPENGL_SHADERS" int))
(define SDL-HINT-RENDER-SCALE-QUALITY (foreign-value "SDL_HINT_RENDER_SCALE_QUALITY" int))
(define SDL-HINT-RENDER-VSYNC (foreign-value "SDL_HINT_RENDER_VSYNC" int))
(define SDL-LOG-CATEGORY-APPLICATION (foreign-value "SDL_LOG_CATEGORY_APPLICATION" int))
(define SDL-LOG-CATEGORY-ERROR (foreign-value "SDL_LOG_CATEGORY_ERROR" int))
(define SDL-LOG-CATEGORY-SYSTEM (foreign-value "SDL_LOG_CATEGORY_SYSTEM" int))
(define SDL-LOG-CATEGORY-AUDIO (foreign-value "SDL_LOG_CATEGORY_AUDIO" int))
(define SDL-LOG-CATEGORY-VIDEO (foreign-value "SDL_LOG_CATEGORY_VIDEO" int))
(define SDL-LOG-CATEGORY-RENDER (foreign-value "SDL_LOG_CATEGORY_RENDER" int))
(define SDL-LOG-CATEGORY-INPUT (foreign-value "SDL_LOG_CATEGORY_INPUT" int))
(define SDL-LOG-CATEGORY-CUSTOM (foreign-value "SDL_LOG_CATEGORY_CUSTOM" int))
(define SDL-LOG-PRIORITY-VERBOSE (foreign-value "SDL_LOG_PRIORITY_VERBOSE" int))
(define SDL-LOG-PRIORITY-DEBUG (foreign-value "SDL_LOG_PRIORITY_DEBUG" int))
(define SDL-LOG-PRIORITY-INFO (foreign-value "SDL_LOG_PRIORITY_INFO" int))
(define SDL-LOG-PRIORITY-WARN (foreign-value "SDL_LOG_PRIORITY_WARN" int))
(define SDL-LOG-PRIORITY-ERROR (foreign-value "SDL_LOG_PRIORITY_ERROR" int))
(define SDL-LOG-PRIORITY-CRITICAL (foreign-value "SDL_LOG_PRIORITY_CRITICAL" int))
(define SDL-WINDOWPOS-CENTERED (foreign-value "SDL_WINDOWPOS_CENTERED" int))
(define SDL-WINDOWPOS-UNDEFINED (foreign-value "SDL_WINDOWPOS_UNDEFINED" int))
(define SDL-WINDOW-FULLSCREEN (foreign-value "SDL_WINDOW_FULLSCREEN" int))
(define SDL-WINDOW-FULLSCREEN-DESKTOP (foreign-value "SDL_WINDOW_FULLSCREEN_DESKTOP" int))
(define SDL-WINDOW-OPENGL (foreign-value "SDL_WINDOW_OPENGL" int))
(define SDL-WINDOW-SHOWN (foreign-value "SDL_WINDOW_SHOWN" int))
(define SDL-WINDOW-HIDDEN (foreign-value "SDL_WINDOW_HIDDEN" int))
(define SDL-WINDOW-BORDERLESS (foreign-value "SDL_WINDOW_BORDERLESS" int))
(define SDL-WINDOW-RESIZABLE (foreign-value "SDL_WINDOW_RESIZABLE" int))
(define SDL-WINDOW-MINIMIZED (foreign-value "SDL_WINDOW_MINIMIZED" int))
(define SDL-WINDOW-MAXIMIZED (foreign-value "SDL_WINDOW_MAXIMIZED" int))
(define SDL-WINDOW-INPUT-GRABBED (foreign-value "SDL_WINDOW_INPUT_GRABBED" int))
(define SDL-WINDOW-INPUT-FOCUS (foreign-value "SDL_WINDOW_INPUT_FOCUS" int))
(define SDL-WINDOW-MOUSE-FOCUS (foreign-value "SDL_WINDOW_MOUSE_FOCUS" int))
(define SDL-WINDOW-FOREIGN (foreign-value "SDL_WINDOW_FOREIGN" int))
(define SDL-GL-RED-SIZE (foreign-value "SDL_GL_RED_SIZE" int))
(define SDL-GL-GREEN-SIZE (foreign-value "SDL_GL_GREEN_SIZE" int))
(define SDL-GL-BLUE-SIZE (foreign-value "SDL_GL_BLUE_SIZE" int))
(define SDL-GL-ALPHA-SIZE (foreign-value "SDL_GL_ALPHA_SIZE" int))
(define SDL-GL-BUFFER-SIZE (foreign-value "SDL_GL_BUFFER_SIZE" int))
(define SDL-GL-DOUBLEBUFFER (foreign-value "SDL_GL_DOUBLEBUFFER" int))
(define SDL-GL-DEPTH-SIZE (foreign-value "SDL_GL_DEPTH_SIZE" int))
(define SDL-GL-STENCIL-SIZE (foreign-value "SDL_GL_STENCIL_SIZE" int))
(define SDL-GL-ACCUM-RED-SIZE (foreign-value "SDL_GL_ACCUM_RED_SIZE" int))
(define SDL-GL-ACCUM-GREEN-SIZE (foreign-value "SDL_GL_ACCUM_GREEN_SIZE" int))
(define SDL-GL-ACCUM-BLUE-SIZE (foreign-value "SDL_GL_ACCUM_BLUE_SIZE" int))
(define SDL-GL-ACCUM-ALPHA-SIZE (foreign-value "SDL_GL_ACCUM_ALPHA_SIZE" int))
(define SDL-GL-STEREO (foreign-value "SDL_GL_STEREO" int))
(define SDL-GL-MULTISAMPLEBUFFERS (foreign-value "SDL_GL_MULTISAMPLEBUFFERS" int))
(define SDL-GL-MULTISAMPLESAMPLES (foreign-value "SDL_GL_MULTISAMPLESAMPLES" int))
(define SDL-GL-ACCELERATED-VISUAL (foreign-value "SDL_GL_ACCELERATED_VISUAL" int))
(define SDL-GL-RETAINED-BACKING (foreign-value "SDL_GL_RETAINED_BACKING" int))
(define SDL-GL-CONTEXT-MAJOR-VERSION (foreign-value "SDL_GL_CONTEXT_MAJOR_VERSION" int))
(define SDL-GL-CONTEXT-MINOR-VERSION (foreign-value "SDL_GL_CONTEXT_MINOR_VERSION" int))
(define SDL-GL-CONTEXT-EGL (foreign-value "SDL_GL_CONTEXT_EGL" int))
(define SDL-GL-CONTEXT-FLAGS (foreign-value "SDL_GL_CONTEXT_FLAGS" int))
(define SDL-GL-CONTEXT-PROFILE-MASK (foreign-value "SDL_GL_CONTEXT_PROFILE_MASK" int))
(define SDL-GL-SHARE-WITH-CURRENT-CONTEXT (foreign-value "SDL_GL_SHARE_WITH_CURRENT_CONTEXT" int))
(define SDL-WINDOW-FULLSCREEN (foreign-value "SDL_WINDOW_FULLSCREEN" int))
(define SDL-WINDOW-FULLSCREEN-DESKTOP (foreign-value "SDL_WINDOW_FULLSCREEN_DESKTOP" int))
(define SDL-QUIT (foreign-value "SDL_QUIT" int))
(define SDL-APP-TERMINATING (foreign-value "SDL_APP_TERMINATING" int))
(define SDL-APP-LOWMEMORY (foreign-value "SDL_APP_LOWMEMORY" int))
(define SDL-APP-WILLENTERBACKGROUND (foreign-value "SDL_APP_WILLENTERBACKGROUND" int))
(define SDL-APP-DIDENTERBACKGROUND (foreign-value "SDL_APP_DIDENTERBACKGROUND" int))
(define SDL-APP-WILLENTERFOREGROUND (foreign-value "SDL_APP_WILLENTERFOREGROUND" int))
(define SDL-APP-DIDENTERFOREGROUND (foreign-value "SDL_APP_DIDENTERFOREGROUND" int))
(define SDL-WINDOWEVENT (foreign-value "SDL_WINDOWEVENT" int))
(define SDL-SYSWMEVENT (foreign-value "SDL_SYSWMEVENT" int))
(define SDL-KEYDOWN (foreign-value "SDL_KEYDOWN" int))
(define SDL-KEYUP (foreign-value "SDL_KEYUP" int))
(define SDL-TEXTEDITING (foreign-value "SDL_TEXTEDITING" int))
(define SDL-TEXTINPUT (foreign-value "SDL_TEXTINPUT" int))
(define SDL-MOUSEMOTION (foreign-value "SDL_MOUSEMOTION" int))
(define SDL-MOUSEBUTTONDOWN (foreign-value "SDL_MOUSEBUTTONDOWN" int))
(define SDL-MOUSEBUTTONUP (foreign-value "SDL_MOUSEBUTTONUP" int))
(define SDL-MOUSEWHEEL (foreign-value "SDL_MOUSEWHEEL" int))
(define SDL-JOYAXISMOTION (foreign-value "SDL_JOYAXISMOTION" int))
(define SDL-JOYBALLMOTION (foreign-value "SDL_JOYBALLMOTION" int))
(define SDL-JOYHATMOTION (foreign-value "SDL_JOYHATMOTION" int))
(define SDL-JOYBUTTONDOWN (foreign-value "SDL_JOYBUTTONDOWN" int))
(define SDL-JOYBUTTONUP (foreign-value "SDL_JOYBUTTONUP" int))
(define SDL-JOYDEVICEADDED (foreign-value "SDL_JOYDEVICEADDED" int))
(define SDL-JOYDEVICEREMOVED (foreign-value "SDL_JOYDEVICEREMOVED" int))
(define SDL-CONTROLLERAXISMOTION (foreign-value "SDL_CONTROLLERAXISMOTION" int))
(define SDL-CONTROLLERBUTTONDOWN (foreign-value "SDL_CONTROLLERBUTTONDOWN" int))
(define SDL-CONTROLLERBUTTONUP (foreign-value "SDL_CONTROLLERBUTTONUP" int))
(define SDL-CONTROLLERDEVICEADDED (foreign-value "SDL_CONTROLLERDEVICEADDED" int))
(define SDL-CONTROLLERDEVICEREMOVED (foreign-value "SDL_CONTROLLERDEVICEREMOVED" int))
(define SDL-CONTROLLERDEVICEREMAPPED (foreign-value "SDL_CONTROLLERDEVICEREMAPPED" int))
(define SDL-FINGERDOWN (foreign-value "SDL_FINGERDOWN" int))
(define SDL-FINGERUP (foreign-value "SDL_FINGERUP" int))
(define SDL-FINGERMOTION (foreign-value "SDL_FINGERMOTION" int))
(define SDL-DOLLARGESTURE (foreign-value "SDL_DOLLARGESTURE" int))
(define SDL-DOLLARRECORD (foreign-value "SDL_DOLLARRECORD" int))
(define SDL-MULTIGESTURE (foreign-value "SDL_MULTIGESTURE" int))
(define SDL-CLIPBOARDUPDATE (foreign-value "SDL_CLIPBOARDUPDATE" int))
(define SDL-DROPFILE (foreign-value "SDL_DROPFILE" int))
(define SDL-USEREVENT (foreign-value "SDL_USEREVENT" int))
(define SDL-PIXELFORMAT-UNKNOWN (foreign-value "SDL_PIXELFORMAT_UNKNOWN" int))
(define SDL-PIXELFORMAT-INDEX1LSB (foreign-value "SDL_PIXELFORMAT_INDEX1LSB" int))
(define SDL-PIXELFORMAT-INDEX1MSB (foreign-value "SDL_PIXELFORMAT_INDEX1MSB" int))
(define SDL-PIXELFORMAT-INDEX4LSB (foreign-value "SDL_PIXELFORMAT_INDEX4LSB" int))
(define SDL-PIXELFORMAT-INDEX4MSB (foreign-value "SDL_PIXELFORMAT_INDEX4MSB" int))
(define SDL-PIXELFORMAT-INDEX8 (foreign-value "SDL_PIXELFORMAT_INDEX8" int))
(define SDL-PIXELFORMAT-RGB332 (foreign-value "SDL_PIXELFORMAT_RGB332" int))
(define SDL-PIXELFORMAT-RGB444 (foreign-value "SDL_PIXELFORMAT_RGB444" int))
(define SDL-PIXELFORMAT-RGB555 (foreign-value "SDL_PIXELFORMAT_RGB555" int))
(define SDL-PIXELFORMAT-BGR555 (foreign-value "SDL_PIXELFORMAT_BGR555" int))
(define SDL-PIXELFORMAT-ARGB4444 (foreign-value "SDL_PIXELFORMAT_ARGB4444" int))
(define SDL-PIXELFORMAT-RGBA4444 (foreign-value "SDL_PIXELFORMAT_RGBA4444" int))
(define SDL-PIXELFORMAT-ABGR4444 (foreign-value "SDL_PIXELFORMAT_ABGR4444" int))
(define SDL-PIXELFORMAT-BGRA4444 (foreign-value "SDL_PIXELFORMAT_BGRA4444" int))
(define SDL-PIXELFORMAT-ARGB1555 (foreign-value "SDL_PIXELFORMAT_ARGB1555" int))
(define SDL-PIXELFORMAT-RGBA5551 (foreign-value "SDL_PIXELFORMAT_RGBA5551" int))
(define SDL-PIXELFORMAT-ABGR1555 (foreign-value "SDL_PIXELFORMAT_ABGR1555" int))
(define SDL-PIXELFORMAT-BGRA5551 (foreign-value "SDL_PIXELFORMAT_BGRA5551" int))
(define SDL-PIXELFORMAT-RGB565 (foreign-value "SDL_PIXELFORMAT_RGB565" int))
(define SDL-PIXELFORMAT-BGR565 (foreign-value "SDL_PIXELFORMAT_BGR565" int))
(define SDL-PIXELFORMAT-RGB24 (foreign-value "SDL_PIXELFORMAT_RGB24" int))
(define SDL-PIXELFORMAT-BGR24 (foreign-value "SDL_PIXELFORMAT_BGR24" int))
(define SDL-PIXELFORMAT-RGB888 (foreign-value "SDL_PIXELFORMAT_RGB888" int))
(define SDL-PIXELFORMAT-RGBX8888 (foreign-value "SDL_PIXELFORMAT_RGBX8888" int))
(define SDL-PIXELFORMAT-BGR888 (foreign-value "SDL_PIXELFORMAT_BGR888" int))
(define SDL-PIXELFORMAT-BGRX8888 (foreign-value "SDL_PIXELFORMAT_BGRX8888" int))
(define SDL-PIXELFORMAT-ARGB8888 (foreign-value "SDL_PIXELFORMAT_ARGB8888" int))
(define SDL-PIXELFORMAT-RGBA8888 (foreign-value "SDL_PIXELFORMAT_RGBA8888" int))
(define SDL-PIXELFORMAT-ABGR8888 (foreign-value "SDL_PIXELFORMAT_ABGR8888" int))
(define SDL-PIXELFORMAT-BGRA8888 (foreign-value "SDL_PIXELFORMAT_BGRA8888" int))
(define SDL-PIXELFORMAT-ARGB2101010 (foreign-value "SDL_PIXELFORMAT_ARGB2101010" int))
(define SDL-PIXELFORMAT-YV12 (foreign-value "SDL_PIXELFORMAT_YV12" int))
(define SDL-PIXELFORMAT-IYUV (foreign-value "SDL_PIXELFORMAT_IYUV" int))
(define SDL-PIXELFORMAT-YUY2 (foreign-value "SDL_PIXELFORMAT_YUY2" int))
(define SDL-PIXELFORMAT-UYVY (foreign-value "SDL_PIXELFORMAT_UYVY" int))
(define SDL-PIXELFORMAT-YVYU (foreign-value "SDL_PIXELFORMAT_YVYU" int))
(define SDL-TEXTUREACCESS-STATIC (foreign-value "SDL_TEXTUREACCESS_STATIC" int))
(define SDL-TEXTUREACCESS-STREAMING (foreign-value "SDL_TEXTUREACCESS_STREAMING" int))
)
