(module sdl2-events
  (sdl-poll-event
   sdl-event-type sdl-event-user sdl-event-key
   SDL-QUIT SDL-KEYUP SDL-KEYDOWN)
  (import scheme chicken foreign)
  (use c-struct)

(foreign-declare "#include <SDL2/SDL_events.h>")

(define-c-struct (sdl-event "SDL_Event")
  (constructor: make-sdl-event)
  (unsigned-integer type sdl-event-type)
  ((struct "SDL_UserEvent") user sdl-event-user)
  ((struct "SDL_KeyboardEvent") key sdl-event-key))

(define-c-struct (sdl-user-event "SDL_UserEvent")
  (constructor: make-sdl-user-event)
  (unsigned-integer type sdl-user-event-type)
  (unsigned-integer timestamp sdl-user-event-timestamp)
  (unsigned-integer windowID sdl-user-event-window-id)
  (integer code sdl-user-event-code)
  (c-pointer data1 sdl-user-event-data1)
  (c-pointer data2 sdl-user-event-data2))

(define-c-struct (sdl-keyboard-event "SDL_KeyboardEvent")
  (constructor: make-sdl-keyboard-event)
  (unsigned-integer type sdl-keyboard-event-type)
  (unsigned-integer timestamp sdl-keyboard-event-time)
  (unsigned-integer windowID sdl-keyboard-event-window-id)
  (byte state sdl-keyboard-event-state)
  (byte repeat sdl-keyboard-event-repeat)
  ((struct "SDL_Keysym") keysym sdl-keyboard-event-keysym))

(define-c-struct (sdl-keysym "SDL_Keysym")
  (constructor: make-sdl-keysym)
  (integer scancode sdl-keysym-scancode)
  (integer sym sdl-keysym-sym)
  (unsigned-short mod sdl-keysym-mod))

(define-c-struct (sdl-mouse-button-event "SDL_MouseButtonEvent")
  (integer x sdl-mouse-button-event-x)
  (integer y sdl-mouse-button-event-y))

(define (sdl-poll-event)
  (let ((e (make-sdl-event)))
    (and (= 1 ((foreign-lambda int "SDL_PollEvent" (c-pointer "SDL_Event"))
               (c-struct->pointer e)))
         e)))

(define SDL-QUIT (foreign-value "SDL_QUIT" int))
(define SDL-APP-TERMINATING (foreign-value "SDL_APP_TERMINATING" int))
(define SDL-APP-LOWMEMORY (foreign-value "SDL_APP_LOWMEMORY" int))
(define SDL-APP-WILLENTERBACKGROUND (foreign-value "SDL_APP_WILLENTERBACKGROUND" int))
(define SDL-APP-DIDENTERBACKGROUND (foreign-value "SDL_APP_DIDENTERBACKGROUND" int))
(define SDL-APP-WILLENTERFOREGROUND (foreign-value "SDL_APP_WILLENTERFOREGROUND" int))
(define SDL-APP-DIDENTERFOREGROUND (foreign-value "SDL_APP_DIDENTERFOREGROUND" int))
(define SDL-WINDOWEVENT (foreign-value "SDL_WINDOWEVENT" int))
(define SDL-SYSWMEVENT (foreign-value "SDL_SYSWMEVENT" int))
(define SDL-KEYDOWN (foreign-value "SDL_KEYDOWN" int))
(define SDL-KEYUP (foreign-value "SDL_KEYUP" int))
(define SDL-TEXTEDITING (foreign-value "SDL_TEXTEDITING" int))
(define SDL-TEXTINPUT (foreign-value "SDL_TEXTINPUT" int))
(define SDL-MOUSEMOTION (foreign-value "SDL_MOUSEMOTION" int))
(define SDL-MOUSEBUTTONDOWN (foreign-value "SDL_MOUSEBUTTONDOWN" int))
(define SDL-MOUSEBUTTONUP (foreign-value "SDL_MOUSEBUTTONUP" int))
(define SDL-MOUSEWHEEL (foreign-value "SDL_MOUSEWHEEL" int))
(define SDL-JOYAXISMOTION (foreign-value "SDL_JOYAXISMOTION" int))
(define SDL-JOYBALLMOTION (foreign-value "SDL_JOYBALLMOTION" int))
(define SDL-JOYHATMOTION (foreign-value "SDL_JOYHATMOTION" int))
(define SDL-JOYBUTTONDOWN (foreign-value "SDL_JOYBUTTONDOWN" int))
(define SDL-JOYBUTTONUP (foreign-value "SDL_JOYBUTTONUP" int))
(define SDL-JOYDEVICEADDED (foreign-value "SDL_JOYDEVICEADDED" int))
(define SDL-JOYDEVICEREMOVED (foreign-value "SDL_JOYDEVICEREMOVED" int))
(define SDL-CONTROLLERAXISMOTION (foreign-value "SDL_CONTROLLERAXISMOTION" int))
(define SDL-CONTROLLERBUTTONDOWN (foreign-value "SDL_CONTROLLERBUTTONDOWN" int))
(define SDL-CONTROLLERBUTTONUP (foreign-value "SDL_CONTROLLERBUTTONUP" int))
(define SDL-CONTROLLERDEVICEADDED (foreign-value "SDL_CONTROLLERDEVICEADDED" int))
(define SDL-CONTROLLERDEVICEREMOVED (foreign-value "SDL_CONTROLLERDEVICEREMOVED" int))
(define SDL-CONTROLLERDEVICEREMAPPED (foreign-value "SDL_CONTROLLERDEVICEREMAPPED" int))
(define SDL-FINGERDOWN (foreign-value "SDL_FINGERDOWN" int))
(define SDL-FINGERUP (foreign-value "SDL_FINGERUP" int))
(define SDL-FINGERMOTION (foreign-value "SDL_FINGERMOTION" int))
(define SDL-DOLLARGESTURE (foreign-value "SDL_DOLLARGESTURE" int))
(define SDL-DOLLARRECORD (foreign-value "SDL_DOLLARRECORD" int))
(define SDL-MULTIGESTURE (foreign-value "SDL_MULTIGESTURE" int))
(define SDL-CLIPBOARDUPDATE (foreign-value "SDL_CLIPBOARDUPDATE" int))
(define SDL-DROPFILE (foreign-value "SDL_DROPFILE" int))
(define SDL-USEREVENT (foreign-value "SDL_USEREVENT" int))
)
